# Generated by Django 3.2.4 on 2021-07-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_image_url_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default1.jpg', upload_to=''),
        ),
    ]
